<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-47169-1660796944/blob/main/Assignment_1_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"
s.split()
print(s)


Hi there Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742
a="The diameter of {planet} is {diameter} kilometers"
print(a.format(planet = "Earth",diameter = 12742))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d1=d['k1'][3]['tricky'][3]['target'][3]
print(d1)

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
b=np.ones(10)*5
print(b)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
a=np.arange(20,35)
print(a)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
a=np.arange(0,8+1).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
import numpy as np
a=np.concatenate((a,b),axis=None)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [12]:
import pandas as pd
d={"a":[10,20,30],"b":[10,20,30]}
df=pd.DataFrame(d)
print(df)

    a   b
0  10  10
1  20  20
2  30  30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [13]:
import datetime
import pandas as pd
test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
K = 40
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [14]:
lists = [[1, 'aaa', 22],[3, 'ccc', 24], [2, 'bbb', 25]]
df=pd.DataFrame(lists,columns=["a","b","c"])
print(df)

   a    b   c
0  1  aaa  22
1  3  ccc  24
2  2  bbb  25
